import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

const translations = {
  en: {
    // Nav
    home: 'Home',
    categories: 'Categories',
    chat: 'AI Chat',
    timeline: 'Timeline',
    checklist: 'Checklist',
    lawyers: 'Find Lawyers',
    processingTimes: 'Processing Times',
    news: 'News',
    glossary: 'Glossary',
    faq: 'FAQ',
    feeCalculator: 'Fee Calculator',
    tools: 'Tools',
    visaBulletin: 'Visa Bulletin',
    toolsMenu: 'Tools menu',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    languageToggleAria: 'Switch language',

    // Tools dropdown descriptions
    toolFeeCalculatorDesc: 'Estimate filing costs',
    toolProcessingTimesDesc: 'Check USCIS times',
    toolChecklistDesc: 'Document checklists',
    toolGlossaryDesc: 'Immigration terms',
    toolVisaBulletinDesc: 'Final action & filing dates',

    // Fee Calculator
    feeCalculatorTitle: 'Visa Fee Calculator',
    feeCalculatorSubtitle: 'Estimate the total cost of your immigration application. Select a form type and configure options to see an itemized breakdown.',
    feeApplicationType: 'Application Type',
    feeSelectVisa: 'Select a visa or application type...',
    feeNumApplicants: 'Number of Applicants',
    feeAdults: 'Adults (14+)',
    feeChildren: 'Children (under 14)',
    feeAdditionalFees: 'Additional Fees',
    feePremiumProcessing: 'Premium Processing',
    feePremiumProcessingDesc: 'Expedited processing (15 business days). Available for select applications (H-1B, I-140, etc.)',
    feeBiometrics: 'Biometrics (Fingerprinting)',
    feeBiometricsDesc: 'Required for most applications. Charged per person.',
    feeMedicalExam: 'Medical Exam (I-693)',
    feeMedicalExamDesc: 'Required for green card applications. Paid directly to USCIS-designated civil surgeon.',
    feeCostBreakdown: 'Cost Breakdown',
    feeSelectToSee: 'Select an application type to see the estimated costs.',
    feeEstimatedTotal: 'Estimated Total',
    feeReset: 'Reset',
    feeDisclaimer: 'Fees are approximate and based on 2024-2025 USCIS fee schedules. Always verify current fees before filing.',
    feeVerifyLink: 'Verify at uscis.gov/fees',
    feeReferenceTitle: 'USCIS Fee Reference (2024-2025)',
    feeRefForm: 'Form',
    feeRefApplication: 'Application',
    feeRefFee: 'Fee',
    feeRefBiometrics: 'Biometrics (Fingerprinting)',
    perPerson: 'per person',
    estimate: 'estimate',

    // Home page
    heroTitle: 'Navigate U.S. Immigration with Confidence',
    heroSubtitle: 'AI-powered guidance for visas, green cards, citizenship, and more. Get clear answers to your immigration questions.',
    searchPlaceholder: 'Search visa types, processes, or questions...',
    howItWorks: 'How It Works',
    step1Title: 'Choose Your Path',
    step1Desc: 'Browse visa categories or describe your situation to find the right immigration option for you.',
    step2Title: 'Get AI Guidance',
    step2Desc: 'Ask our AI assistant any immigration question and receive detailed, accurate answers instantly.',
    step3Title: 'Take Action',
    step3Desc: 'Follow step-by-step checklists, track timelines, and connect with qualified immigration lawyers.',
    recentNews: 'Recent Immigration News',
    quickAccess: 'Quick Access',
    homeAskBadge: 'AI Assistant',
    homeAskTitle: 'Ask ImmigrationIQ — Your AI Immigration Assistant',
    homeAskSubtitle: 'Get instant answers to your U.S. immigration questions.',
    homeAskInputPlaceholder: 'Ask anything — visas, green cards, citizenship…',
    homePopularCategories: 'Popular Categories',
    homeLatestNewsTitle: 'Latest Immigration News',
    homeLatestNewsIntro: 'The latest U.S. immigration headlines — USCIS policy, visa bulletins, executive orders, and court decisions.',
    homeVisaBulletinDashTitle: 'Visa Bulletin Dashboard',
    homeVisaBulletinDashIntro: 'Track Final Action Dates and Dates for Filing for the most popular family- and employment-based categories.',
    fullPageView: 'Full Page View',
    homeChatPrompt1: 'How do I apply for a green card through marriage?',
    homeChatPrompt2: 'What are the H-1B requirements for FY 2027?',
    homeChatPrompt3: 'How long does naturalization take in 2026?',
    homeChatPrompt4: 'Can I file Adjustment of Status under the May 2026 visa bulletin?',
    homeAITrained: 'Trained on USCIS guidance, visa bulletins, and immigration law — available 24/7 in English & Spanish.',

    // Visa Bulletin page
    visaBulletinPageIntro: "The U.S. Department of State publishes the Visa Bulletin monthly. Use the toggles below to switch between Final Action Dates and Dates for Filing, and between family- and employment-based categories.",
    visaBulletinMonth: 'Month',
    visaBulletinLatest: 'latest',
    visaBulletinHowToRead: 'How to read this bulletin',
    visaBulletinHowToReadBody: "Find the row for your preference category and the column for your country of chargeability. If your priority date is *earlier* than the date shown, you may proceed with the next step in your case. The dates use the State Department's DDMMMYY format (e.g. 01JAN16 = January 1, 2016). \"C\" means Current — no waiting.",
    visaBulletinNotSurePD: 'Not sure what your priority date is?',
    visaBulletinNotSurePDBody: 'Ask the AI assistant — it can walk through your case category and help you read the bulletin.',
    visaBulletinAskBtn: 'Ask ImmigrationIQ',
    visaBulletinTitle: 'Visa Bulletin',
    visaBulletinDesc: 'The Visa Bulletin is published monthly by the U.S. Department of State. It shows which immigrant visa applicants can move forward with their cases based on their priority date and preference category.',
    visaBulletinPriorityDate: 'What is a Priority Date?',
    visaBulletinPriorityDateDesc: 'Your Priority Date is the date your immigration petition was filed (or, for some categories, the date your labor certification was filed). The Visa Bulletin shows "Final Action Dates" and "Dates for Filing" — if your priority date is earlier than the date listed for your category and country, you may be eligible to proceed. If the bulletin shows "C" (Current), no waiting is required for that category.',
    visaBulletinCta: 'View Official Visa Bulletin',

    // Common
    learnMore: 'Learn More',
    askAI: 'Ask AI',
    viewAll: 'View All',
    search: 'Search',
    filter: 'Filter',
    download: 'Download',
    print: 'Print',
    export: 'Export',
    copyMessage: 'Copy',
    startChat: 'Start Chat',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    getStarted: 'Get Started',
    all: 'All',
    readMore: 'Read More',
    explain: 'Explain',
    askFollowUp: 'Ask follow-up',
    disclaimer: 'This tool provides general information only and is not legal advice. Consult a qualified immigration attorney for your specific situation.',
    noResults: 'No results found.',

    // Chat
    chatTitle: 'Immigration AI Assistant',
    chatSubtitle: 'Ask any question about U.S. immigration processes, visas, or requirements.',
    chatPlaceholder: 'Type your immigration question...',
    chatSuggestion1: 'What are the requirements for an H-1B visa?',
    chatSuggestion2: 'How do I apply for a green card through marriage?',
    chatSuggestion3: 'What is the difference between B-1 and B-2 visas?',
    typing: 'Typing...',
    chatThinking: 'Thinking…',
    chatNewChat: 'New Chat',
    chatNewChatTitle: 'Start a new chat',
    chatNewChatConfirm: 'Start a new chat? This will clear the current conversation.',
    chatSend: 'Send',
    chatSendAria: 'Send message',
    chatExportPdf: 'Export PDF',
    chatHintBefore: 'Press',
    chatHintEnter: 'to send',
    chatHintShift: 'Shift',
    chatHintEnterKey: 'Enter',
    chatHintNewLine: 'for new line',
    chatEmptyHelper: 'Ask any question about U.S. immigration — visas, green cards, citizenship, and more.',
    chatErrorGeneric: 'Failed to get a response. Please try again.',
    chatErrorNetwork: 'Network error. Please check your internet connection and try again.',
    chatErrorNoText: 'No text content in API response',
    chatRateLimitReached: "You've reached the daily limit of {limit} questions. Please come back tomorrow!",
    chatRemaining: '{count}/{limit} questions remaining today',
    chatLabelYou: 'You',
    chatLabelAssistant: 'ImmigrationIQ',
    copyMessageAria: 'Copy message',
    floatingChatLabel: 'Ask ImmigrationIQ',
    floatingChatAria: 'Ask ImmigrationIQ — AI Assistant',
    exportChat: 'Export Chat',
    chatExportTitle: 'ImmigrationIQ - Chat History',
    chatExportTimestamp: 'Exported on',
    chatExportYou: 'You',
    chatExportAi: 'AI Assistant',
    chatExportDisclaimer: 'Disclaimer: This chat provides general information only and is not legal advice. Consult a qualified immigration attorney for your specific situation.',

    // Category
    overview: 'Overview',
    eligibility: 'Eligibility',
    process: 'Process',
    documents: 'Documents',
    forms: 'Forms',
    costs: 'Costs',
    mistakes: 'Common Mistakes',
    afterApproval: 'After Approval',
    relatedVisas: 'Related Visas',
    difficultyEasy: 'Easy',
    difficultyModerate: 'Moderate',
    difficultyComplex: 'Complex',
    categoriesIntro: 'Explore all U.S. immigration categories, visas, and processes',
    categoriesNoResults: 'No categories found matching your search.',

    // FAQ
    faqIntro: 'Frequently asked questions about U.S. immigration, organized by topic.',
    faqSearchPlaceholder: 'Search FAQs...',
    faqNoResults: 'No FAQs match your search.',

    // Lawyers
    lawyersIntro: 'Find qualified immigration attorneys and learn how to protect yourself from scams.',
    lawyersWarningTitle: 'Important: This is NOT a referral service',
    lawyersWarningBody: "Always verify an attorney's credentials independently. Only licensed attorneys and DOJ-accredited representatives can legally provide immigration services.",
    tabHowToChoose: 'How to Choose',
    tabFindLawyer: 'Find a Lawyer',
    tabFreeLegalAid: 'Free Legal Aid',
    whatToLookFor: 'What to Look For',
    questionsToAsk: 'Questions to Ask in a Consultation',
    redFlagsTitle: 'Red Flags / Immigration Scams',
    notarioWarningTitle: 'CRITICAL WARNING: Notario Fraud',
    notSureLawyerTitle: 'Not sure what type of lawyer you need?',
    notSureLawyerBody: 'Describe your situation and our AI will suggest what type of immigration attorney specialty to look for.',
    describeMySituation: 'Describe My Situation',

    // News
    newsIntro: 'Latest immigration policy updates, visa bulletins, and court decisions.',
    newsSearchPlaceholder: 'Search news...',
    newsNoResults: 'No news articles match your criteria.',
    newsSubscribeTitle: 'Stay Updated',
    newsSubscribeBody: 'Get immigration news and policy updates delivered to your inbox.',
    newsSubscribe: 'Subscribe',
    newsSubscribeNote: 'Feature coming soon. No data is collected.',
    newsCatAll: 'All',
    newsCatUscis: 'USCIS Policy',
    newsCatVisaBulletins: 'Visa Bulletins',
    newsCatExecutive: 'Executive Orders',
    newsCatCourt: 'Court Decisions',
    newsCatFee: 'Fee Changes',

    // Timeline
    timelineIntro: 'Select your immigration scenario to see a detailed timeline with milestones and estimated durations.',
    timelineSelectScenario: 'Select Your Scenario',
    timelineYourTimeline: 'Your Timeline',

    // Checklist
    checklistIntro: 'Generate a personalized document checklist based on your visa type and personal situation.',
    checklistStep1: 'Step 1: Select Visa Type',
    checklistStep2: 'Step 2: Your Situation',
    checklistChooseVisa: '-- Choose a visa category --',
    checklistDocChecklist: 'Document Checklist',
    situationMarried: 'Married',
    situationChildren: 'Has Children',
    situationEmployed: 'Currently Employed',

    // Glossary
    glossaryIntro: 'A-Z glossary of U.S. immigration terms and definitions.',
    glossarySearchPlaceholder: 'Search terms...',
    glossaryNoResults: 'No terms match your search.',
    glossaryExample: 'Example:',
    glossaryRelated: 'Related:',
    glossaryExplainSimply: 'Explain Simply',

    // Processing Times
    processingTimesIntro: 'Estimated processing times by form and service center. Last updated:',
    processingTimesCheckRealtime: 'Check real-time data at USCIS.gov',
    processingTimesFilters: 'Filters',
    processingTimesFormType: 'Form Type',
    processingTimesAllForms: 'All Forms',
    processingTimesServiceCenter: 'Service Center',
    processingTimesAllCenters: 'All Centers',
    processingTimesComparison: 'Processing Comparison (minimum months)',
    processingTimesReceiptToDecision: 'Receipt to Decision',
    processingTimesProcessingTime: 'Processing Time',

    // Footer
    about: 'About',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    contact: 'Contact Us',
    copyright: '© 2026 ImmigrationIQ. All rights reserved.',
    footerAbout: 'AI-powered guidance for navigating the U.S. immigration system. Get clear answers, step-by-step processes, and document checklists.',
    footerQuickLinks: 'Quick Links',
    footerOfficialResources: 'Official Resources',
    footerLegal: 'Legal',
    footerLegal1: 'ImmigrationIQ is NOT legal advice.',
    footerLegal2: 'Laws change frequently — verify at uscis.gov.',
    footerLegal3: 'Consult a licensed immigration attorney.',
    footerLegal4: 'BEWARE of notarios and unauthorized practitioners.',

    // Contact page
    contactTitle: 'Contact Us',
    contactIntro: 'Have a question, partnership idea, or feedback? We\'d love to hear from you.',
    contactEmailLabel: 'Email us directly',
    contactFormHeading: 'Send us a message',
    contactFieldName: 'Full Name',
    contactFieldEmail: 'Email',
    contactFieldPhone: 'Phone (optional)',
    contactFieldSubject: 'Subject',
    contactFieldMessage: 'Message',
    contactPlaceholderName: 'Jane Doe',
    contactPlaceholderEmail: 'you@example.com',
    contactPlaceholderPhone: '(555) 123-4567',
    contactPlaceholderMessage: 'Tell us how we can help...',
    contactSelectSubject: 'Select a subject...',
    contactSubjectGeneral: 'General Inquiry',
    contactSubjectPartnership: 'Advertising / Partnership',
    contactSubjectListing: 'Legal Professional Listing',
    contactSubjectBug: 'Bug Report',
    contactSubjectOther: 'Other',
    contactSubmit: 'Send Message',
    contactSubmitting: 'Sending...',
    contactSuccess: 'Thanks! Your message has been sent. We\'ll be in touch soon.',
    contactError: 'Something went wrong. Please try again or email us directly.',
    contactRequired: 'Required',
    contactPartnershipTitle: 'For Lawyers & Businesses',
    contactPartnershipBody: 'ImmigrationIQ reaches thousands of immigrants and prospective applicants searching for trustworthy guidance. We offer partnership opportunities for licensed immigration attorneys, legal-aid organizations, and immigration-related service providers.',
    contactPartnershipBullet1: 'Featured lawyer directory listings with state and practice-area targeting',
    contactPartnershipBullet2: 'Sponsored content and educational article placements',
    contactPartnershipBullet3: 'Bilingual (English / Spanish) audience reach',
    contactPartnershipBullet4: 'Co-branded checklists, guides, and lead-generation programs',
    contactPartnershipCta: 'Reach out using the form on this page — select "Advertising / Partnership" — and our team will follow up within two business days.',
    contactDisclaimer: 'We are not a law firm. For legal advice, consult an immigration attorney.',

    // Newsletter signup
    newsletterTitle: 'Stay Updated on Immigration News',
    newsletterSubtitle: 'Get policy changes, USCIS updates, and visa bulletin highlights delivered to your inbox. No spam, unsubscribe anytime.',
    newsletterFooterTitle: 'Immigration News in Your Inbox',
    newsletterFooterSubtitle: 'Monthly updates on policy and processing times.',
    newsletterEmailPlaceholder: 'your@email.com',
    newsletterSubmit: 'Subscribe',
    newsletterSubmitting: 'Subscribing...',
    newsletterSuccess: 'Thanks for subscribing! Check your inbox to confirm.',
    newsletterError: 'Something went wrong. Please try again.',
    newsletterPrivacy: 'We respect your privacy. Unsubscribe with one click.',

    // Lawyer directory
    tabDirectory: 'Directory',
    lawyersDirectoryIntro: 'Browse immigration attorneys by location and practice area.',
    lawyersGetListedTitle: 'Are you an immigration attorney? Get listed here!',
    lawyersGetListedBody: 'Reach thousands of bilingual readers actively researching their immigration options. Featured listings include placement at the top of search results, your firm logo, and direct links to your consultation booking page.',
    lawyersGetListedCta: 'Contact us to be listed',
    lawyersFilterState: 'State',
    lawyersFilterPractice: 'Practice Area',
    lawyersFilterAll: 'All',
    lawyersResultsCount: '{count} attorneys',
    lawyersFeatured: 'Featured',
    lawyersScheduleConsultation: 'Schedule Consultation',
    lawyersWebsite: 'Visit website',
    lawyersLanguagesLabel: 'Languages',
    lawyersPracticeAreasLabel: 'Practice areas',
    lawyersNoResults: 'No attorneys match your filters. Try different criteria.',
    lawyersDirectoryDisclaimer: 'Listings include featured paid placements and are not endorsements. Always verify state bar credentials independently before hiring an attorney.',
    practiceAreaFamily: 'Family',
    practiceAreaEmployment: 'Employment',
    practiceAreaAsylum: 'Asylum',
    practiceAreaDeportation: 'Deportation Defense',
    practiceAreaCitizenship: 'Citizenship',

    // Premium services / document kits
    services: 'Premium',
    servicesTitle: 'Professional Document Preparation Kits',
    servicesIntro: 'Step-by-step guides, evidence checklists, sample letters, and form walkthroughs to help you prepare your immigration application with confidence. New kits releasing soon.',
    servicesComingSoon: 'Coming Soon',
    servicesDisclaimer: 'These kits provide guidance only. They are not legal advice. For complex cases, consult a licensed immigration attorney.',
    kitMarriageTitle: 'Green Card through Marriage Kit',
    kitMarriageDesc: 'Step-by-step I-130 + I-485 filing instructions, evidence checklist for proving a bona fide marriage, sample cover letters, and interview preparation questions.',
    kitNaturalizationTitle: 'Naturalization / Citizenship Checklist',
    kitNaturalizationDesc: 'N-400 walkthrough, civics test study materials, document checklist, English/civics interview tips, and post-approval next steps.',
    kitH1bTitle: 'H-1B Visa Application Guide',
    kitH1bDesc: 'Cap-subject filing instructions, sample employer support letters, RFE response strategies, premium processing guidance, and timeline expectations.',
    kitDacaTitle: 'DACA Renewal Kit',
    kitDacaDesc: 'I-821D and I-765 form guide, renewal evidence checklist, fee waiver instructions, deadline tracker, and tips for avoiding common mistakes.',
    kitI130Title: 'Family Petition (I-130) Complete Guide',
    kitI130DescUS: 'Petitioning relatives abroad or adjusting status in the U.S., priority date tracking, supporting document checklist, and processing time expectations.',
    kitAsylumTitle: 'Asylum Application Preparation Kit',
    kitAsylumDesc: 'I-589 form walkthrough, personal declaration writing guide, country conditions evidence, credible fear interview preparation, and one-year filing deadline tips.',

    // Translation status notice (only shown in non-English when content stays English)
    contentLanguageNotice: '',
  },

  es: {
    // Nav
    home: 'Inicio',
    categories: 'Categorías',
    chat: 'Chat IA',
    timeline: 'Cronograma',
    checklist: 'Lista de Verificación',
    lawyers: 'Buscar Abogados',
    processingTimes: 'Tiempos de Procesamiento',
    news: 'Noticias',
    glossary: 'Glosario',
    faq: 'Preguntas Frecuentes',
    feeCalculator: 'Calculadora de Tarifas',
    tools: 'Herramientas',
    visaBulletin: 'Boletín de Visas',
    toolsMenu: 'Menú de herramientas',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    languageEnglish: 'English',
    languageSpanish: 'Español',
    languageToggleAria: 'Cambiar idioma',

    // Tools dropdown descriptions
    toolFeeCalculatorDesc: 'Estima costos de presentación',
    toolProcessingTimesDesc: 'Consulta tiempos de USCIS',
    toolChecklistDesc: 'Listas de documentos',
    toolGlossaryDesc: 'Términos de inmigración',
    toolVisaBulletinDesc: 'Fechas de acción final y presentación',

    // Fee Calculator
    feeCalculatorTitle: 'Calculadora de Tarifas de Visa',
    feeCalculatorSubtitle: 'Estima el costo total de tu solicitud de inmigración. Selecciona un tipo de formulario y configura opciones para ver un desglose detallado.',
    feeApplicationType: 'Tipo de Solicitud',
    feeSelectVisa: 'Selecciona una visa o tipo de solicitud...',
    feeNumApplicants: 'Número de Solicitantes',
    feeAdults: 'Adultos (14+)',
    feeChildren: 'Niños (menores de 14)',
    feeAdditionalFees: 'Tarifas Adicionales',
    feePremiumProcessing: 'Procesamiento Premium',
    feePremiumProcessingDesc: 'Procesamiento acelerado (15 días hábiles). Disponible para solicitudes seleccionadas (H-1B, I-140, etc.)',
    feeBiometrics: 'Biométricos (Huellas Digitales)',
    feeBiometricsDesc: 'Requerido para la mayoría de solicitudes. Se cobra por persona.',
    feeMedicalExam: 'Examen Médico (I-693)',
    feeMedicalExamDesc: 'Requerido para solicitudes de tarjeta de residencia. Pagado directamente al cirujano civil designado por USCIS.',
    feeCostBreakdown: 'Desglose de Costos',
    feeSelectToSee: 'Selecciona un tipo de solicitud para ver los costos estimados.',
    feeEstimatedTotal: 'Total Estimado',
    feeReset: 'Restablecer',
    feeDisclaimer: 'Las tarifas son aproximadas y se basan en las tarifas de USCIS 2024-2025. Verifica siempre las tarifas actuales antes de presentar.',
    feeVerifyLink: 'Verifica en uscis.gov/fees',
    feeReferenceTitle: 'Referencia de Tarifas USCIS (2024-2025)',
    feeRefForm: 'Formulario',
    feeRefApplication: 'Solicitud',
    feeRefFee: 'Tarifa',
    feeRefBiometrics: 'Biométricos (Huellas Digitales)',
    perPerson: 'por persona',
    estimate: 'estimado',

    // Home page
    heroTitle: 'Navega la Inmigración a EE.UU. con Confianza',
    heroSubtitle: 'Orientación impulsada por IA para visas, tarjetas de residencia, ciudadanía y más. Obtén respuestas claras a tus preguntas de inmigración.',
    searchPlaceholder: 'Buscar tipos de visa, procesos o preguntas...',
    howItWorks: 'Cómo Funciona',
    step1Title: 'Elige Tu Camino',
    step1Desc: 'Explora las categorías de visa o describe tu situación para encontrar la opción de inmigración adecuada para ti.',
    step2Title: 'Obtén Orientación con IA',
    step2Desc: 'Haz cualquier pregunta de inmigración a nuestro asistente de IA y recibe respuestas detalladas y precisas al instante.',
    step3Title: 'Toma Acción',
    step3Desc: 'Sigue listas de verificación paso a paso, rastrea cronogramas y conéctate con abogados de inmigración calificados.',
    recentNews: 'Noticias Recientes de Inmigración',
    quickAccess: 'Acceso Rápido',
    homeAskBadge: 'Asistente IA',
    homeAskTitle: 'Pregunta a ImmigrationIQ — Tu Asistente de Inmigración con IA',
    homeAskSubtitle: 'Obtén respuestas instantáneas a tus preguntas sobre inmigración a EE.UU.',
    homeAskInputPlaceholder: 'Pregunta lo que sea — visas, tarjetas de residencia, ciudadanía…',
    homePopularCategories: 'Categorías Populares',
    homeLatestNewsTitle: 'Últimas Noticias de Inmigración',
    homeLatestNewsIntro: 'Las últimas noticias de inmigración a EE.UU. — política de USCIS, boletines de visas, órdenes ejecutivas y decisiones judiciales.',
    homeVisaBulletinDashTitle: 'Panel del Boletín de Visas',
    homeVisaBulletinDashIntro: 'Rastrea las Fechas de Acción Final y Fechas para Presentar de las categorías más populares basadas en familia y empleo.',
    fullPageView: 'Ver Página Completa',
    homeChatPrompt1: '¿Cómo solicito una tarjeta de residencia por matrimonio?',
    homeChatPrompt2: '¿Cuáles son los requisitos H-1B para el año fiscal 2027?',
    homeChatPrompt3: '¿Cuánto tarda la naturalización en 2026?',
    homeChatPrompt4: '¿Puedo presentar Ajuste de Estatus bajo el boletín de visas de mayo 2026?',
    homeAITrained: 'Entrenado con la guía de USCIS, boletines de visas y la ley de inmigración — disponible 24/7 en inglés y español.',

    // Visa Bulletin page
    visaBulletinPageIntro: 'El Departamento de Estado de EE.UU. publica el Boletín de Visas mensualmente. Usa los interruptores a continuación para alternar entre Fechas de Acción Final y Fechas para Presentar, y entre categorías basadas en familia y empleo.',
    visaBulletinMonth: 'Mes',
    visaBulletinLatest: 'más reciente',
    visaBulletinHowToRead: 'Cómo leer este boletín',
    visaBulletinHowToReadBody: 'Encuentra la fila para tu categoría de preferencia y la columna para tu país de cargo. Si tu fecha de prioridad es *anterior* a la fecha mostrada, puedes proceder con el siguiente paso de tu caso. Las fechas usan el formato DDMMMYY del Departamento de Estado (p. ej., 01JAN16 = 1 de enero de 2016). "C" significa Corriente — sin espera.',
    visaBulletinNotSurePD: '¿No estás seguro de cuál es tu fecha de prioridad?',
    visaBulletinNotSurePDBody: 'Pregúntale al asistente de IA — puede guiarte a través de la categoría de tu caso y ayudarte a leer el boletín.',
    visaBulletinAskBtn: 'Preguntar a ImmigrationIQ',
    visaBulletinTitle: 'Boletín de Visas',
    visaBulletinDesc: 'El Boletín de Visas es publicado mensualmente por el Departamento de Estado de EE.UU. Muestra qué solicitantes de visa de inmigrante pueden avanzar con sus casos según su fecha de prioridad y categoría de preferencia.',
    visaBulletinPriorityDate: '¿Qué es una Fecha de Prioridad?',
    visaBulletinPriorityDateDesc: 'Tu Fecha de Prioridad es la fecha en que se presentó tu petición de inmigración (o, para algunas categorías, la fecha en que se presentó tu certificación laboral). El Boletín de Visas muestra "Fechas de Acción Final" y "Fechas para Presentar" — si tu fecha de prioridad es anterior a la fecha indicada para tu categoría y país, puedes ser elegible para proceder. Si el boletín muestra "C" (Corriente), no se requiere espera para esa categoría.',
    visaBulletinCta: 'Ver Boletín de Visas Oficial',

    // Common
    learnMore: 'Más Información',
    askAI: 'Preguntar a IA',
    viewAll: 'Ver Todo',
    search: 'Buscar',
    filter: 'Filtrar',
    download: 'Descargar',
    print: 'Imprimir',
    export: 'Exportar',
    copyMessage: 'Copiar',
    startChat: 'Iniciar Chat',
    back: 'Volver',
    next: 'Siguiente',
    previous: 'Anterior',
    getStarted: 'Comenzar',
    all: 'Todas',
    readMore: 'Leer Más',
    explain: 'Explicar',
    askFollowUp: 'Hacer pregunta de seguimiento',
    disclaimer: 'Esta herramienta proporciona solo información general y no constituye asesoría legal. Consulta a un abogado de inmigración calificado para tu situación específica.',
    noResults: 'No se encontraron resultados.',

    // Chat
    chatTitle: 'Asistente de Inmigración IA',
    chatSubtitle: 'Haz cualquier pregunta sobre procesos de inmigración, visas o requisitos en EE.UU.',
    chatPlaceholder: 'Escribe tu pregunta de inmigración...',
    chatSuggestion1: '¿Cuáles son los requisitos para una visa H-1B?',
    chatSuggestion2: '¿Cómo solicito una tarjeta de residencia por matrimonio?',
    chatSuggestion3: '¿Cuál es la diferencia entre las visas B-1 y B-2?',
    typing: 'Escribiendo...',
    chatThinking: 'Pensando…',
    chatNewChat: 'Nuevo Chat',
    chatNewChatTitle: 'Iniciar un nuevo chat',
    chatNewChatConfirm: '¿Iniciar un nuevo chat? Esto borrará la conversación actual.',
    chatSend: 'Enviar',
    chatSendAria: 'Enviar mensaje',
    chatExportPdf: 'Exportar PDF',
    chatHintBefore: 'Presiona',
    chatHintEnter: 'para enviar',
    chatHintShift: 'Shift',
    chatHintEnterKey: 'Enter',
    chatHintNewLine: 'para nueva línea',
    chatEmptyHelper: 'Haz cualquier pregunta sobre inmigración a EE.UU. — visas, tarjetas de residencia, ciudadanía y más.',
    chatErrorGeneric: 'No se pudo obtener una respuesta. Por favor intenta de nuevo.',
    chatErrorNetwork: 'Error de red. Verifica tu conexión a internet e intenta de nuevo.',
    chatErrorNoText: 'La respuesta de la API no contiene texto',
    chatRateLimitReached: 'Has alcanzado el límite diario de {limit} preguntas. ¡Vuelve mañana!',
    chatRemaining: '{count}/{limit} preguntas restantes hoy',
    chatLabelYou: 'Tú',
    chatLabelAssistant: 'ImmigrationIQ',
    copyMessageAria: 'Copiar mensaje',
    floatingChatLabel: 'Pregunta a ImmigrationIQ',
    floatingChatAria: 'Pregunta a ImmigrationIQ — Asistente IA',
    exportChat: 'Exportar Chat',
    chatExportTitle: 'ImmigrationIQ - Historial de Chat',
    chatExportTimestamp: 'Exportado el',
    chatExportYou: 'Tú',
    chatExportAi: 'Asistente IA',
    chatExportDisclaimer: 'Aviso: Este chat proporciona solo información general y no constituye asesoría legal. Consulta a un abogado de inmigración calificado para tu situación específica.',

    // Category
    overview: 'Descripción General',
    eligibility: 'Elegibilidad',
    process: 'Proceso',
    documents: 'Documentos',
    forms: 'Formularios',
    costs: 'Costos',
    mistakes: 'Errores Comunes',
    afterApproval: 'Después de la Aprobación',
    relatedVisas: 'Visas Relacionadas',
    difficultyEasy: 'Fácil',
    difficultyModerate: 'Moderado',
    difficultyComplex: 'Complejo',
    categoriesIntro: 'Explora todas las categorías de inmigración a EE.UU., visas y procesos',
    categoriesNoResults: 'No se encontraron categorías que coincidan con tu búsqueda.',

    // FAQ
    faqIntro: 'Preguntas frecuentes sobre inmigración a EE.UU., organizadas por tema.',
    faqSearchPlaceholder: 'Buscar preguntas frecuentes...',
    faqNoResults: 'Ninguna pregunta frecuente coincide con tu búsqueda.',

    // Lawyers
    lawyersIntro: 'Encuentra abogados de inmigración calificados y aprende a protegerte de estafas.',
    lawyersWarningTitle: 'Importante: Esto NO es un servicio de referencia',
    lawyersWarningBody: 'Verifica siempre las credenciales de un abogado de forma independiente. Solo abogados con licencia y representantes acreditados por el DOJ pueden brindar legalmente servicios de inmigración.',
    tabHowToChoose: 'Cómo Elegir',
    tabFindLawyer: 'Buscar un Abogado',
    tabFreeLegalAid: 'Asistencia Legal Gratuita',
    whatToLookFor: 'Qué Buscar',
    questionsToAsk: 'Preguntas para Hacer en una Consulta',
    redFlagsTitle: 'Señales de Alerta / Estafas de Inmigración',
    notarioWarningTitle: 'ADVERTENCIA CRÍTICA: Fraude de Notarios',
    notSureLawyerTitle: '¿No sabes qué tipo de abogado necesitas?',
    notSureLawyerBody: 'Describe tu situación y nuestra IA te sugerirá qué especialidad de abogado de inmigración buscar.',
    describeMySituation: 'Describir Mi Situación',

    // News
    newsIntro: 'Últimas actualizaciones de política de inmigración, boletines de visas y decisiones judiciales.',
    newsSearchPlaceholder: 'Buscar noticias...',
    newsNoResults: 'Ningún artículo de noticias coincide con tus criterios.',
    newsSubscribeTitle: 'Mantente Actualizado',
    newsSubscribeBody: 'Recibe noticias y actualizaciones de política de inmigración en tu correo.',
    newsSubscribe: 'Suscribirse',
    newsSubscribeNote: 'Función próximamente. No se recopilan datos.',
    newsCatAll: 'Todas',
    newsCatUscis: 'Política de USCIS',
    newsCatVisaBulletins: 'Boletines de Visas',
    newsCatExecutive: 'Órdenes Ejecutivas',
    newsCatCourt: 'Decisiones Judiciales',
    newsCatFee: 'Cambios de Tarifas',

    // Timeline
    timelineIntro: 'Selecciona tu escenario de inmigración para ver un cronograma detallado con hitos y duraciones estimadas.',
    timelineSelectScenario: 'Selecciona Tu Escenario',
    timelineYourTimeline: 'Tu Cronograma',

    // Checklist
    checklistIntro: 'Genera una lista de documentos personalizada según tu tipo de visa y situación personal.',
    checklistStep1: 'Paso 1: Selecciona Tipo de Visa',
    checklistStep2: 'Paso 2: Tu Situación',
    checklistChooseVisa: '-- Elige una categoría de visa --',
    checklistDocChecklist: 'Lista de Documentos',
    situationMarried: 'Casado/a',
    situationChildren: 'Tiene Hijos',
    situationEmployed: 'Empleado Actualmente',

    // Glossary
    glossaryIntro: 'Glosario A-Z de términos y definiciones de inmigración a EE.UU.',
    glossarySearchPlaceholder: 'Buscar términos...',
    glossaryNoResults: 'Ningún término coincide con tu búsqueda.',
    glossaryExample: 'Ejemplo:',
    glossaryRelated: 'Relacionado:',
    glossaryExplainSimply: 'Explica de Forma Sencilla',

    // Processing Times
    processingTimesIntro: 'Tiempos estimados de procesamiento por formulario y centro de servicio. Última actualización:',
    processingTimesCheckRealtime: 'Consulta datos en tiempo real en USCIS.gov',
    processingTimesFilters: 'Filtros',
    processingTimesFormType: 'Tipo de Formulario',
    processingTimesAllForms: 'Todos los Formularios',
    processingTimesServiceCenter: 'Centro de Servicio',
    processingTimesAllCenters: 'Todos los Centros',
    processingTimesComparison: 'Comparación de Procesamiento (meses mínimos)',
    processingTimesReceiptToDecision: 'De Recibo a Decisión',
    processingTimesProcessingTime: 'Tiempo de Procesamiento',

    // Footer
    about: 'Acerca de',
    privacy: 'Política de Privacidad',
    terms: 'Términos de Servicio',
    contact: 'Contáctanos',
    copyright: '© 2026 ImmigrationIQ. Todos los derechos reservados.',
    footerAbout: 'Orientación impulsada por IA para navegar el sistema de inmigración de EE.UU. Obtén respuestas claras, procesos paso a paso y listas de documentos.',
    footerQuickLinks: 'Enlaces Rápidos',
    footerOfficialResources: 'Recursos Oficiales',
    footerLegal: 'Legal',
    footerLegal1: 'ImmigrationIQ NO es asesoría legal.',
    footerLegal2: 'Las leyes cambian frecuentemente — verifica en uscis.gov.',
    footerLegal3: 'Consulta a un abogado de inmigración con licencia.',
    footerLegal4: 'CUIDADO con notarios y profesionales no autorizados.',

    // Contact page
    contactTitle: 'Contáctanos',
    contactIntro: '¿Tienes una pregunta, una idea de colaboración o comentarios? Nos encantaría saber de ti.',
    contactEmailLabel: 'Escríbenos directamente',
    contactFormHeading: 'Envíanos un mensaje',
    contactFieldName: 'Nombre completo',
    contactFieldEmail: 'Correo electrónico',
    contactFieldPhone: 'Teléfono (opcional)',
    contactFieldSubject: 'Asunto',
    contactFieldMessage: 'Mensaje',
    contactPlaceholderName: 'María Pérez',
    contactPlaceholderEmail: 'tu@ejemplo.com',
    contactPlaceholderPhone: '(555) 123-4567',
    contactPlaceholderMessage: 'Cuéntanos cómo podemos ayudarte...',
    contactSelectSubject: 'Selecciona un asunto...',
    contactSubjectGeneral: 'Consulta General',
    contactSubjectPartnership: 'Publicidad / Colaboración',
    contactSubjectListing: 'Listado de Profesional Legal',
    contactSubjectBug: 'Reporte de Error',
    contactSubjectOther: 'Otro',
    contactSubmit: 'Enviar Mensaje',
    contactSubmitting: 'Enviando...',
    contactSuccess: '¡Gracias! Tu mensaje fue enviado. Nos pondremos en contacto pronto.',
    contactError: 'Algo salió mal. Inténtalo de nuevo o escríbenos directamente.',
    contactRequired: 'Requerido',
    contactPartnershipTitle: 'Para Abogados y Empresas',
    contactPartnershipBody: 'ImmigrationIQ llega a miles de inmigrantes y solicitantes potenciales que buscan orientación confiable. Ofrecemos oportunidades de colaboración para abogados de inmigración con licencia, organizaciones de asistencia legal y proveedores de servicios relacionados con inmigración.',
    contactPartnershipBullet1: 'Listados destacados en el directorio de abogados, segmentados por estado y área de práctica',
    contactPartnershipBullet2: 'Contenido patrocinado y publicación de artículos educativos',
    contactPartnershipBullet3: 'Audiencia bilingüe (inglés / español)',
    contactPartnershipBullet4: 'Listas de verificación, guías y programas de captación de clientes con marca compartida',
    contactPartnershipCta: 'Escríbenos usando el formulario en esta página — selecciona "Publicidad / Colaboración" — y nuestro equipo te responderá en un plazo de dos días hábiles.',
    contactDisclaimer: 'No somos un bufete de abogados. Para asesoría legal, consulta a un abogado de inmigración.',

    // Newsletter signup
    newsletterTitle: 'Mantente Informado sobre Noticias de Inmigración',
    newsletterSubtitle: 'Recibe cambios de políticas, actualizaciones de USCIS y aspectos destacados del boletín de visas en tu correo. Sin spam, cancela cuando quieras.',
    newsletterFooterTitle: 'Noticias de Inmigración en tu Correo',
    newsletterFooterSubtitle: 'Actualizaciones mensuales sobre políticas y tiempos de procesamiento.',
    newsletterEmailPlaceholder: 'tu@email.com',
    newsletterSubmit: 'Suscribirse',
    newsletterSubmitting: 'Suscribiendo...',
    newsletterSuccess: '¡Gracias por suscribirte! Revisa tu correo para confirmar.',
    newsletterError: 'Algo salió mal. Por favor intenta de nuevo.',
    newsletterPrivacy: 'Respetamos tu privacidad. Cancela con un clic.',

    // Lawyer directory
    tabDirectory: 'Directorio',
    lawyersDirectoryIntro: 'Explora abogados de inmigración por ubicación y área de práctica.',
    lawyersGetListedTitle: '¿Es usted abogado de inmigración? ¡Aparezca aquí!',
    lawyersGetListedBody: 'Llegue a miles de lectores bilingües que están investigando activamente sus opciones de inmigración. Los listados destacados incluyen colocación en la parte superior de los resultados, el logotipo de su firma y enlaces directos a su página de reserva de consultas.',
    lawyersGetListedCta: 'Contáctanos para aparecer',
    lawyersFilterState: 'Estado',
    lawyersFilterPractice: 'Área de Práctica',
    lawyersFilterAll: 'Todos',
    lawyersResultsCount: '{count} abogados',
    lawyersFeatured: 'Destacado',
    lawyersScheduleConsultation: 'Agendar Consulta',
    lawyersWebsite: 'Visitar sitio web',
    lawyersLanguagesLabel: 'Idiomas',
    lawyersPracticeAreasLabel: 'Áreas de práctica',
    lawyersNoResults: 'Ningún abogado coincide con tus filtros. Prueba con otros criterios.',
    lawyersDirectoryDisclaimer: 'Los listados incluyen colocaciones pagas destacadas y no son avales. Verifica siempre las credenciales del colegio de abogados estatal antes de contratar a un abogado.',
    practiceAreaFamily: 'Familia',
    practiceAreaEmployment: 'Empleo',
    practiceAreaAsylum: 'Asilo',
    practiceAreaDeportation: 'Defensa contra Deportación',
    practiceAreaCitizenship: 'Ciudadanía',

    // Premium services / document kits
    services: 'Premium',
    servicesTitle: 'Kits Profesionales de Preparación de Documentos',
    servicesIntro: 'Guías paso a paso, listas de evidencias, cartas de muestra y recorridos de formularios para ayudarte a preparar tu solicitud de inmigración con confianza. Nuevos kits próximamente.',
    servicesComingSoon: 'Próximamente',
    servicesDisclaimer: 'Estos kits brindan orientación únicamente. No constituyen asesoría legal. Para casos complejos, consulta a un abogado de inmigración con licencia.',
    kitMarriageTitle: 'Kit de Green Card por Matrimonio',
    kitMarriageDesc: 'Instrucciones paso a paso para presentar I-130 + I-485, lista de evidencias para demostrar un matrimonio de buena fe, cartas de presentación de muestra y preguntas de preparación para la entrevista.',
    kitNaturalizationTitle: 'Lista de Verificación de Naturalización / Ciudadanía',
    kitNaturalizationDesc: 'Guía del formulario N-400, materiales de estudio del examen cívico, lista de documentos, consejos para la entrevista de inglés/cívica y próximos pasos tras la aprobación.',
    kitH1bTitle: 'Guía de Solicitud de Visa H-1B',
    kitH1bDesc: 'Instrucciones para presentaciones sujetas a cupo, cartas de apoyo del empleador de muestra, estrategias de respuesta a RFE, orientación sobre procesamiento premium y expectativas de tiempo.',
    kitDacaTitle: 'Kit de Renovación de DACA',
    kitDacaDesc: 'Guía de los formularios I-821D y I-765, lista de evidencias para renovación, instrucciones de exención de tarifa, rastreador de plazos y consejos para evitar errores comunes.',
    kitI130Title: 'Guía Completa de Petición Familiar (I-130)',
    kitI130DescUS: 'Petición para familiares en el extranjero o ajuste de estatus en EE.UU., seguimiento de fechas de prioridad, lista de documentos de respaldo y expectativas de tiempo de procesamiento.',
    kitAsylumTitle: 'Kit de Preparación de Solicitud de Asilo',
    kitAsylumDesc: 'Guía del formulario I-589, redacción de la declaración personal, evidencia de condiciones del país, preparación para la entrevista de miedo creíble y consejos sobre el plazo de presentación de un año.',

    // Translation status notice (shown when content stays English)
    contentLanguageNotice: 'Algunos artículos de fondo (preguntas frecuentes, biografías de abogados, titulares de noticias) aún se muestran en inglés. Estamos traduciendo el contenido completo.',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      return localStorage.getItem('immigrationiq-language') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = useCallback((lang) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('immigrationiq-language', lang);
    } catch {
      // localStorage unavailable
    }
  }, []);

  // Reflect language in <html lang> for accessibility / SEO
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language === 'es' ? 'es' : 'en';
    }
  }, [language]);

  const t = useCallback(
    (key) => {
      const value = translations[language]?.[key];
      if (value !== undefined) return value;
      return translations.en?.[key] ?? key;
    },
    [language]
  );

  const value = React.useMemo(
    () => ({ language, setLanguage, t }),
    [language, setLanguage, t]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
